# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatoGrapher_auth', '0003_auto_20171207_1703'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('subscriber', 'subscribe_to')]),
        ),
    ]
