# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatoGrapher', '0002_auto_20171201_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.ImageField(upload_to='media/CatoGrapher/photos/'),
        ),
    ]
